import React from "react";
import Head from "next/head";
import Hero from "../components/Hero";
import About from "../components/About";

export default function Home() {
  React.useEffect(() => {
    if (typeof window !== "undefined") {
      window.history.scrollRestoration = "manual";
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-[2000px]">
        <Hero />
        <About />
      </main>
    </>
  );
}
